default: &default
  airflow:
    host: <%= ENV.fetch("AIRFLOW_WEBSERVER_HOST", "localhost:8080") %>
    filename_pattern: !ruby/regexp "/wo_[a-z0-9_]+/"
    api:
      list_tasks: /admin/rest_api/api?api=list_tasks&dag_id=%{dag_id}
      trigger_dag: /admin/rest_api/api?api=trigger_dag&dag_id=%{dag_id}&run_id=%{run_id}&conf=%{configs}

development:
  <<: *default

test:
  <<: *default